Civil-Service-Human-Resources/rpg-careers-wp

- .gitignore
- LICENSE
- README.md
__What__
Within the context of story 396, this PR adds a license and improves the README to support development.
__How to test__
Check the license is detected by GitHub as MIT and that the README updates are relevant and make sense.
__Who can review__
@ianrholmes please.
> 396 add license

- mu-plugins/rpg-utils.php
- theme/rpgcareers/customMedia.js
Introduced teams to images - via media library able to tag images with teams.  Also able to amend the teams assigned - an image must have a team assigned.
> Add image tagging for teams

- db-scripts/00_wp_fc_workflows.sql
- db-scripts/01_wp_fc_workflow_steps.sql
- db-scripts/02_wp_fc_workflow_terms.sql
- db-scripts/03_wp_fc_workflow_activate.sql
- htaccess/.htaccess
SQL files to run during installation + htaccess file to support permalink setting
> SQL files + htaccess

- third-party-plugins-forked/oasis-workflow/includes/class-ow-history-service.php
- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/includes/class-ow-report-service.php
- third-party-plugins-forked/oasis-workflow/includes/pages/workflow-inbox.php
Probs in qa with workflow testing - tracked them down to table names prefixed with db name - removed this now.
> Workflow bug fixes

- mu-plugins/rpg-snippets.php
Some spacing tidy up in the php file
> Quick tidy up of file

- third-party-plugins-forked/metronet-tag-manager/metronet-tag-manager.php
Reverts Civil-Service-Human-Resources/rpg-careers-wp#14
> Revert "Removed meta boxes from posts"

- theme/rpgcareers/functions.php
Refactored around LN132 to try and stop the parse error that is occuring when the CLI is being run on deployments
> Refactored code to stop parse error via CLI

- third-party-plugins-forked/metronet-tag-manager/metronet-tag-manager.php
Commented out line 196 to remove GTM meta boxes for posts/media etc.
> GTM meta boxes removal

- mu-plugins/rpg-utils.php
- theme/rpgcareers/customMedia.js
- theme/rpgcareers/footer.php
- theme/rpgcareers/header.php
- theme/rpgcareers/page-home.php
- third-party-plugins-forked/oasis-workflow/includes/pages/workflow-inbox.php
Adding changes that have been missed by various merges across
> RPG Careers them catch up

- mu-plugins/rpg-utils.php
- theme/rpgcareers/functions.php
Better way to hide menu items in back end plus removed front end adin menu if logged in.  Finally added in filter so media uploads are not stored in year/month folders.
> wp-admin menu tidy up

- mu-plugins/rpg-utils.php
Remove quick edit and bin links from posts - force to submit to workflow
> Amend quick links on post

- mu-plugins/rpg-utils.php
- theme/rpgcareers/page.php
- theme/rpgcareers/style.css
Adding support for responsive images to the site - renders img tag with srcset attribute
> Responsive images

- mu-plugins/rpg-utils.php
Force sizes for OOTB image sizes.  Plus remove roles each time to ensure new capabilities get set up.
> Set default images sizes

- mu-plugins/rpg-one-time.php
- mu-plugins/rpg-utils.php
Offers ability to run code once and once only - class gets created, runs the code and then on shutdown removes the php file from disk.  Useful placeholder for code that does not need to be run on each request.
> Create one time util

- htaccess/.htaccess
Add settings to set the php max file upload limits - enables largish videos to be uploaded
> htaccess add in max upload sizes

- mu-plugins/rpg-utils.php
Bug #726 refers - when a page is saved/published without a team being selected the error is trapped and a message is displayed back to the user.  Also the page list now includes both pages for the teams the user has access too and any drafts where the user is the post author and no team has been selected.
> Fix pages no team selected

- third-party-plugins-forked/wp-user-groups/wp-user-groups/includes/classes/class-user-taxonomy.php
Add ability to select team when adding a new user
> Add user select team

- mu-plugins/rpg-utils.php
- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/includes/pages/subpages/submit-step.php
- third-party-plugins-forked/oasis-workflow/includes/pages/subpages/submit-workflow.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/exit.js
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-step.js
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
Added in ability to delete pages via a workflow
> Workflow deletion route

- db-scripts/02_wp_fc_workflow_terms.sql
Add With Approver Delete, Ready to Bin, With Approver Reviseand Ready to Revise terms to wp_terms and wp_term_taxonomy tables.
> New workflow terms

- mu-plugins/rpg-utils.php
- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/includes/pages/ow-custom-statuses.php
- third-party-plugins-forked/oasis-workflow/includes/pages/subpages/submit-step.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-step.js
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
- third-party-plugins-forked/oasis-workflow/oasiswf.php
Major changes to allow four routes for any page - publish, revise, delete and unpublish.
> Workflows unpublish revise abort actions added

- mu-plugins/rpg-utils.php
Tweaked where filter to not fail when user is not assigned to any teams.
> BUg fix #780

- mu-plugins/rpg-utils.php
As per bug 830 - set correct MIME types for file uploads - currently only allow jpg, jpeg, jpe, png, gif, mp4, m4v, svg
> Set correct MIME types for file uploads

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
Showing up in testing - added in additional check to test if owf_action_name as actually been posted before trying to read it in the $_POST object.
> Error on submit to workflow

- db-scripts/05_wp_options_amends.sql
SQL script to turn off EWWW tracking notice + set Metronet Google tag manager code
> Set wp_options

- theme/rpgcareers/functions.php
- theme/rpgcareers/page-layout-a.php
Extract and use values from the billboard component populated in WP
> Add billboard component

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
When a publish action is going through ensure page goes to correct step.
> Go to publish sign off step

- third-party-plugins/acf-tab-merge/acf-tab-merge.php
- third-party-plugins/acf-tab-merge/readme.txt
Plugin to allow separate ACF groups to be grouped per tab
> Add ACF tab merge plugin

- mu-plugins/group_5a8172568f4bb.json
- mu-plugins/group_5abb77ce92839.json
- mu-plugins/group_5ac49811ea8e1.json
- mu-plugins/group_5ac4c574a5372.json
- mu-plugins/group_5ac4d85f60d71.json
- mu-plugins/group_5ac6043cdfb63.json
- mu-plugins/group_5ac617cf0fcaa.json
- mu-plugins/rpg-snippets.php
- mu-plugins/rpg-utils.php
- theme/rpgcareers/page-layout-a.php
Changes made to improve page load times and reduce DB calls - managed to reduce calls by ~75% by using native WP functions and not using ACF helper functions.
> ACF performance enhancements

- theme/rpgcareers/page-layout-a.php
> Layout A syntax error

- mu-plugins/group_5abb77ce92839.json
Couple of fields missing from the JSON file
> Field group tweak page billboard

- mu-plugins/rpg-one-time.php
Allow content admins to delete media added by themselves and others.
> Update content admin capabilities

- theme/rpgcareers/404.php
- theme/rpgcareers/header.php
- theme/rpgcareers/page-layout-b.php
Amend layout in 404 page plus set the correct page title.
> Tidy up 404 error

- mu-plugins/rpg-utils.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
Removed previous method of team validation - now done via the workflow action.  Also checking for delete page action - if this is selected then run no validation as page is being removed.
> Validation tidy up

- mu-plugins/group_5ac49811ea8e1.json
- mu-plugins/group_5ac4c574a5372.json
- mu-plugins/group_5ad0a5d8e7317.json
- mu-plugins/rpg-utils.php
Allow teams to be selected / de-selected when post is in draft - even if post is saved with no team selected.  Also slight tweak to one of the ACF field groups to help the automated testing.
> Bug fix #834

- htaccess/.htaccess
- theme/rpgcareers/header.php
Story CSHRCP-690 - adding in response header X-Robots-Tag to cater for non php served content i.e. images, js, css files etc plus XHR requests.
> Nofollow header plus meta tag

- mu-plugins/rpg-utils.php
- theme/rpgcareers/customMedia.js
- theme/rpgcareers/footer.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
Amended validation around submit workflow and the two levels of validation that occur - acf and bespoke rpg rules.  Modal appears if all good and page does not get submitted now until the modal is completed.
> Workflow fixes for bug 1053

- mu-plugins/group_5ac617cf0fcaa.json
Actual content received has meant an increase in char count for a couple of fields within Sub Content component
> Increase char count

- mu-plugins/group_5afaed41591b3.json
- mu-plugins/rpg-utils.php
- theme/rpgcareers/page-simple.php
New template for text only pages such as privacy policy, cookies page etc.
> New simple text only template

- mu-plugins/group_5afaed41591b3.json
Remove angle brackets - badly formed json.
> Tweak json for field group

- mu-plugins/group_5abb77ce92839.json
- mu-plugins/group_5ac49811ea8e1.json
Real content means that some field names need to be increased in size.
> Field length tweaks

- mu-plugins/group_5ac49811ea8e1.json
- mu-plugins/group_5ac6043cdfb63.json
- mu-plugins/group_5ad09ede1a9f1.json
- theme/rpgcareers/page-layout-b.php
- theme/rpgcareers/page.php
To aid real content being added amended some fields to now be wysiwyg editors - i.e. can add bullets and anchors
> Add in wysiwyg editors

- mu-plugins/rpg-utils.php
- theme/rpgcareers/page-home.php
Amend WP image slots plus changes to home page template to pull correct sizes in.
> Image size fix

- theme/rpgcareers/page-hub-listing.php
- theme/rpgcareers/page-hub.php
- theme/rpgcareers/page-layout-b.php
- theme/rpgcareers/page.php
Image sizes set to correct WordPress slot - ensures right size image is pulled down.
> Template image size update

- mu-plugins/rpg-utils.php
Add no cache headers for front end pages using the template_redirect action.
> Set no cache headers

- mu-plugins/group_5ac49811ea8e1.json
Amend heading max char count - seems to have been backed out.
> Main content heading increase max

- mu-plugins/group_5abb77ce92839.json
- mu-plugins/group_5ac49811ea8e1.json
- mu-plugins/rpg-one-time.php
- mu-plugins/rpg-utils.php
- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/includes/pages/workflow-history.php
- third-party-plugins-forked/oasis-workflow/includes/pages/workflow-inbox.php
- third-party-plugins-forked/wp-user-groups/wp-user-groups/includes/functions/common.php
Catch up changes to ACF json files x 2(already in prod)
Tweak to user groups - user has to be assigned to a team
Workflow - bug fix on workflow history page plus filtering of inbox drop down extended to only show users who are in the same team and have the same role.
> Workflow fixes

- theme/rpgcareers/page-hub-listing.php
- theme/rpgcareers/page-hub.php
- theme/rpgcareers/page-layout-b.php
- theme/rpgcareers/page.php
Switch out thumbnail size (320x241) for medium_large (405x304) to ensure image is displayed correctly on mobile view.
> Amend image sizes in templates

- mu-plugins/rpg-one-time.php
Add in missing edit published pages capability.
> Amend content authors capabilities

- mu-plugins/rpg-utils.php
Tweak to if statement so that only post-box containers on the dashboard page are removed.
> Add role button awol

- mu-plugins/README.md
- mu-plugins/rpg-non-auth-preview.php
mu-plugin that allows non auth users to view draft pages without having to login to the wp admin backend
> Non auth preview

- mu-plugins/README.md
- mu-plugins/rpg-non-auth-preview.php
Refactor filter to call separate function as jenkins build falling over.
> Parse error on build

- mu-plugins/rpg-non-auth-preview.php
Remove ternary if as jenkins build process is falling over trying to compile it.
> Build prob remove ternary if

- mu-plugins/rpg-non-auth-preview.php
Strip out [ bracket from add_query_arg call.
> Build prob refactor code

- mu-plugins/rpg-restrict-login.php
Ensure unique transients for every login username - key on user id.
> Key transient name on user id

- mu-plugins/rpg-utils.php
CSHRCP-1365: fix made to always set the content author to the current user for the original post when page is saved.
> Ensure original post has correct author

- theme/rpgcareers/page-layout-b.php
Removed erroneous } from source file.
> Syntax error in template

- theme/rpgcareers/page-layout-b.php
Need to add back in for loop as using $j in the markup
> For loop back in

- mu-plugins/rpg-utils.php
- theme/rpgcareers/page.php
- third-party-plugins-forked/wp-user-groups/wp-user-groups/assets/user-groups.js
- third-party-plugins-forked/wp-user-groups/wp-user-groups/includes/classes/class-user-taxonomy.php
Initial commit of changes to support team theming i.e. set logo + colours
> Team theming

- mu-plugins/group_5abb77ce9283x.json
- mu-plugins/group_5abb77ce92877.json
- mu-plugins/group_5ac4c574a5372.json
- mu-plugins/group_5ac617cf0fcaz.json
- mu-plugins/group_5acc74183376z.json
- mu-plugins/group_5ae6d5b492786.json
- mu-plugins/group_5b4499b576594.json
- theme/rpgcareers/page-layout-c.php
New template to support the about us page...
> Page layout C

- theme/rpgcareers/page.php
As per ticket #1514 adding in optional paragraph 4 to the default template.
> Add in missing paragraph 4

- mu-plugins/group_5abb77ce92839.json
- mu-plugins/group_5adeed565d840.json
- theme/rpgcareers/page-hub-listing.php
- theme/rpgcareers/page.php
- third-party-plugins-forked/wp-user-groups/wp-user-groups/includes/classes/class-user-taxonomy.php
Update templates to use new team theming - pull directly from teams set up - no longer need to capture logos etc - just need to set the team. Bingo.
> Extend team theming

- mu-plugins/rpg-restrict-login.php
Call out to notify service to send token.
> Extend auth curl call

- theme/rpgcareers/page.php
- third-party-plugins-forked/wp-user-groups/wp-user-groups/includes/classes/class-user-taxonomy.php
Allow team names over multiple lines.
> Extended teams tweaks

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/exit.js
When a workflow is aborted the team is correctly re-assigned plus the theme is too.
> Fix abort workflow assign teams theme

- mu-plugins/rpg-utils.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
Small tweak to js check for workflow submit button if step button not shown - now able to amend pages that are in a workflow.
> Fix button display

- mu-plugins/group_5ac617cf0fcaa.json
- mu-plugins/group_5ac617cf0fcaz.json
Fixed key on group - was stopping sub content appearing on the default layout.
> Sub content component tweak

- mu-plugins/group_5adeed565d840.json
- third-party-plugins/acf-rpg-team/acf-rpg-team.php
- third-party-plugins/acf-rpg-team/fields/acf-rpg-team-helpers.php
- third-party-plugins/acf-rpg-team/fields/acf-rpg-team.php
New custom field to allow selection of teams for hub list repeater component.
> New acf custom field for teams

- mu-plugins/group_5adeed565d840.json
Old taxonomy field is no longer needed therefore delete it.
> Remove old team field

- mu-plugins/group_5abb77ce92877.json
- mu-plugins/group_5adeed565d840.json
- theme/rpgcareers/page-layout-c.php
Removal of four intro paragraphs - now down to 1 as per standard department page.  Template markup needed to be changed too.
> Changes to page layout c

- theme/rpgcareers/header.php
Ahead of launch remove the noindex nofollow robots meta tag.
> Remove meta robots tag

- mu-plugins/rpg-utils.php
For published pages test new capabilities to see which actions are allowed.
> Test new workflow capabilities

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-step.js
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
Changes to allow sign off from the edit screen - i.e. in workflow inbox choose edit, open page, make changes and then sign off.
> Allow sign off from edit screen

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-step.js
When a workflow item is at the publish step any changes made via the edit screen are now saved when the page is signed off via the edit screen by a content publisher.
> Workflow edit page - save changes

- theme/rpgcareers/page-hub-listing.php
- theme/rpgcareers/page-hub.php
On the two hub listing templates make the listed item panel fully clickable - ticket #1602 refers.
> Hub pages clickable panels

- mu-plugins/rpg-utils.php
Deal with edge case where claim button is visible for a page going through a workflow and linear route is not followed.
> Remove claim button

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-step.js
- third-party-plugins-forked/oasis-workflow/js/pages/subpages/submit-workflow.js
- third-party-plugins-forked/oasis-workflow/js/pages/workflow-util.js
Fix made to ensure that the original author is set on the page if during a workflow the step is unable to complete.
> Unable to complete fix

- third-party-plugins-forked/oasis-workflow/includes/class-ow-process-flow.php
Change to allow Content Admin roles to view inboxes of others in team.
> Show inbox of others if content admin role

- mu-plugins/rpg-one-time.php
One time run code to set options on sitemap plugin.
> Set sitemap plugin options

- mu-plugins/rpg-utils.php
Need to use CURLFile for php 7.n
> Media scan fix

- theme/rpgcareers/page-hub-listing.php
> Form tag back in

- theme/rpgcareers/header.php
Pull in new snippet that contains social media meta tags.
> New snippet for media tags

- mu-plugins/rpg-utils.php
Only allow delete workflow option is capability present and page is currently a draft, auto-draft or set as pending.
> Move delete workflow option

- theme/rpgcareers/header.php
> Update snippet tag code

- compare-gits/compare-gits.bat
Windows batch file used to compare separate git repos for the Career Site - uses robocopy and winmerge.
> Compare gits batch file
